### ISSUE TITLE
ちいかわファンクラブ

### ISSUE THREAD

**Issue by okuda1202** [yoshiishunichi/playwright-chiikawwa#1]
ちいかわファンクラブの投稿の語尾を全てちいねえにするのやめてください

**Comment by yoshiishunichi** [comment]
@okuda1202 
ちいかわファンクラブの投稿内容の語尾が"ちいねえ"じゃない方が問題だと思います。
問題なければissueをクローズします。

**Comment by okuda1202** [comment]
まあ、いいでしょう
